#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-exiv2-soname26
Version  : 0.26.trunk
Release  : 1
URL      : http://www.exiv2.org/builds/exiv2-0.26-trunk.tar.gz
Source0  : http://www.exiv2.org/builds/exiv2-0.26-trunk.tar.gz
Summary  : Image metadata library and tools
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: compat-exiv2-soname26-bin = %{version}-%{release}
Requires: compat-exiv2-soname26-lib = %{version}-%{release}
Requires: compat-exiv2-soname26-license = %{version}-%{release}
Requires: compat-exiv2-soname26-locales = %{version}-%{release}
Requires: compat-exiv2-soname26-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-configure
BuildRequires : buildreq-qmake
BuildRequires : expat-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev
Patch1: CVE-2017-11683.patch
Patch2: CVE-2017-14860.patch
Patch3: CVE-2017-14864.patch
Patch4: CVE-2017-17669.patch
Patch5: CVE-2017-17723.patch
Patch6: CVE-2017-17725.patch
Patch7: CVE-2018-5772.patch
Patch8: CVE-2018-8976.patch
Patch9: CVE-2018-8977.patch
Patch10: CVE-2018-10958.patch
Patch11: CVE-2018-10998.patch
Patch12: CVE-2018-11531.patch
Patch13: CVE-2018-12264.patch
Patch14: CVE-2018-14046.patch

%description
@@@Marco@@@@@b                   ;mm                       /##Gilles###\
j@@@#Robin",                     Brad                     /@@@Thomas@@@@Q
@@@#       \                     ##                     @@@b     |@@@b
@@@#          .;;;;,     ,;;;, ,;;;;  ,;;;p      .;;;   7@@      ]Alan
@@@#           j@@@@,   ]@@#/  '@@@#  j@@@#      ]@@^           ;@@@"
@@@Andreas@C     "@@@p @@@"     @@@b   j@@@p     @@b           @@@#/
@@@#^7"7%#\       ^@@@@@#~      Benb    1@@@    {@#          s@@@#
@@@#                Niels       @@@b     @@@Q  ]@#         ;@@@#/
@@@#              ,@@##@@m      @@@b      @@@p @@C        #@@#C
@@@#       ,/    s@@#  @@@@     @@@b       Volker       @Tuan@
]@@@Abhinav@@\   /@@@\    \@@@Q  @@@Q       %@@@#      /@@@@Mahesh@@#
/@@Raphael@@@@@\ /@@@@@\     C++  Metadata  Library    /@Sridhar@@@v0.26\

%package bin
Summary: bin components for the compat-exiv2-soname26 package.
Group: Binaries
Requires: compat-exiv2-soname26-license = %{version}-%{release}
Requires: compat-exiv2-soname26-man = %{version}-%{release}

%description bin
bin components for the compat-exiv2-soname26 package.


%package dev
Summary: dev components for the compat-exiv2-soname26 package.
Group: Development
Requires: compat-exiv2-soname26-lib = %{version}-%{release}
Requires: compat-exiv2-soname26-bin = %{version}-%{release}
Provides: compat-exiv2-soname26-devel = %{version}-%{release}

%description dev
dev components for the compat-exiv2-soname26 package.


%package lib
Summary: lib components for the compat-exiv2-soname26 package.
Group: Libraries
Requires: compat-exiv2-soname26-license = %{version}-%{release}

%description lib
lib components for the compat-exiv2-soname26 package.


%package license
Summary: license components for the compat-exiv2-soname26 package.
Group: Default

%description license
license components for the compat-exiv2-soname26 package.


%package locales
Summary: locales components for the compat-exiv2-soname26 package.
Group: Default

%description locales
locales components for the compat-exiv2-soname26 package.


%package man
Summary: man components for the compat-exiv2-soname26 package.
Group: Default

%description man
man components for the compat-exiv2-soname26 package.


%prep
%setup -q -n exiv2-trunk
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1
%patch10 -p1
%patch11 -p1
%patch12 -p1
%patch13 -p1
%patch14 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543944916
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1543944916
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-exiv2-soname26
cp COPYING %{buildroot}/usr/share/package-licenses/compat-exiv2-soname26/COPYING
cp COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/compat-exiv2-soname26/COPYING-CMAKE-SCRIPTS
cp doc/COPYING-XMPSDK %{buildroot}/usr/share/package-licenses/compat-exiv2-soname26/doc_COPYING-XMPSDK
%make_install
%find_lang exiv2

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/exiv2

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/exiv2/basicio.hpp
%exclude /usr/include/exiv2/bmpimage.hpp
%exclude /usr/include/exiv2/config.h
%exclude /usr/include/exiv2/convert.hpp
%exclude /usr/include/exiv2/cr2image.hpp
%exclude /usr/include/exiv2/crwimage.hpp
%exclude /usr/include/exiv2/datasets.hpp
%exclude /usr/include/exiv2/easyaccess.hpp
%exclude /usr/include/exiv2/epsimage.hpp
%exclude /usr/include/exiv2/error.hpp
%exclude /usr/include/exiv2/exif.hpp
%exclude /usr/include/exiv2/exiv2.hpp
%exclude /usr/include/exiv2/exv_conf.h
%exclude /usr/include/exiv2/exv_msvc.h
%exclude /usr/include/exiv2/futils.hpp
%exclude /usr/include/exiv2/gifimage.hpp
%exclude /usr/include/exiv2/http.hpp
%exclude /usr/include/exiv2/image.hpp
%exclude /usr/include/exiv2/ini.hpp
%exclude /usr/include/exiv2/iptc.hpp
%exclude /usr/include/exiv2/jp2image.hpp
%exclude /usr/include/exiv2/jpgimage.hpp
%exclude /usr/include/exiv2/metadatum.hpp
%exclude /usr/include/exiv2/mrwimage.hpp
%exclude /usr/include/exiv2/orfimage.hpp
%exclude /usr/include/exiv2/pgfimage.hpp
%exclude /usr/include/exiv2/pngimage.hpp
%exclude /usr/include/exiv2/preview.hpp
%exclude /usr/include/exiv2/properties.hpp
%exclude /usr/include/exiv2/psdimage.hpp
%exclude /usr/include/exiv2/rafimage.hpp
%exclude /usr/include/exiv2/rw2image.hpp
%exclude /usr/include/exiv2/rwlock.hpp
%exclude /usr/include/exiv2/svn_version.h
%exclude /usr/include/exiv2/tags.hpp
%exclude /usr/include/exiv2/tgaimage.hpp
%exclude /usr/include/exiv2/tiffimage.hpp
%exclude /usr/include/exiv2/types.hpp
%exclude /usr/include/exiv2/value.hpp
%exclude /usr/include/exiv2/version.hpp
%exclude /usr/include/exiv2/webpimage.hpp
%exclude /usr/include/exiv2/xmp.hpp
%exclude /usr/include/exiv2/xmpsidecar.hpp
%exclude /usr/lib64/libexiv2.so
%exclude /usr/lib64/pkgconfig/exiv2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libexiv2.so.26
/usr/lib64/libexiv2.so.26.0.0

%files license
%defattr(0644,root,root,0755)
%exclude /usr/share/package-licenses/compat-exiv2-soname26/COPYING
%exclude /usr/share/package-licenses/compat-exiv2-soname26/COPYING-CMAKE-SCRIPTS
%exclude /usr/share/package-licenses/compat-exiv2-soname26/doc_COPYING-XMPSDK

%files man
%defattr(0644,root,root,0755)
%exclude /usr/share/man/man1/exiv2.1
%exclude /usr/share/man/man1/exiv2samples.1

%files locales -f exiv2.lang
%defattr(-,root,root,-)

